name: github_explorer
description: "A beautiful Flutter application for exploring GitHub repositories with clean architecture."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    # State management
    get: ^4.6.6

    # HTTP client
    dio: ^5.4.0

    # Local storage
    shared_preferences: ^2.2.2

    # UI components
    cached_network_image: ^3.3.0
    shimmer: ^3.0.0

    # Icons
    flutter_svg: ^2.0.9

    # Utils
    intl: ^0.19.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    flutter_launcher_icons: "^0.14.4"

flutter:
    uses-material-design: true

    assets:
        - assets/images/

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    web:
        generate: true
        background_color: "#62b9fb"
        theme_color: "#62b9fb"
    windows:
        generate: true
        icon_size: 48
    macos:
        generate: true
    image_path: "assets/images/logo.png"
    image_path_android: "assets/images/logo.png"
    image_path_ios: "assets/images/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/logo.png"
